#!/bin/bash

#setup environment
setenforce 0
echo umask 0022 >> /etc/profile
# update security limits
cat /limits.conf >> /etc/security/limits.conf

#enable ssh
cat /root/.ssh/id_rsa.pub > /root/.ssh/authorized_keys

# enable networking
FQDN=$(hostname -f)
echo "NETWORKING=yes" > /etc/sysconfig/network
echo HOSTNAME=$FQDN >> /etc/sysconfig/network
echo 200 overlay >> /etc/iproute2/rt_tables
ip rule add from $(hostname -i | cut -f1 -d " ") table overlay
ip route add default via $(getent hosts overlay-gatewaynode | cut -f1 -d " ") dev eth0 table overlay
sed -i "s/hostname=localhost/hostname=${AMBARI_SERVER}/g" /etc/ambari-agent/conf/ambari-agent.ini
#sed -i "s/HOSTNAME=localhost/HOSTNAME=$(hostname -f)/g" /etc/sysconfig/network

# updates hosts file
cat /hosts >> /etc/hosts

# create hdfs user to test ulimit issue
useradd hdfs -m -s /bin/bash -u 1001

service sshd restart
service ambari-agent restart
/usr/sbin/sshd -d -p 2222
